["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                  XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
"X                  XXXXXXXXXXXX XXXXXXXXXXXXX         XXXXXXXXXXXXXXXXX                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X",
"X                  XXXXXXXXXXX   XXXXXXXXXX              XXXXXXXXXXXXX                                                                 XXXXXXXXXXX             X",
"X                  XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXX                                                                   XXXXXXXX               X",
"X                  XXXXXXXXXXXXXXXXXXXXXXXO E                XXXXXXXX                                                        X   X  X X  XXXXXXX               X",
"X             XXX  XXXXXXXXXXXXXXXXXXXXXXX XXXX               XXXXXXX                                                       X X X X  X   XXXXXX                X",
"X        XXX               XXXXXXXXXXXXXX                      XXXXXX                              O  E         O           X X  X  X X  XXXXX          LXXXXXXX",
"X  LXXX                    XXXXXXXXXXXXXX            E  E O     XXXXX                O      E       XXXXXXXXXXXX   E  O                  XXXXX          LXXXXXXX",
"X  L                       XXXXX  XXXXXX            XXXXXX      XXXXXX                XXXXXXXXXXXXXX            XXXXXX                  XXXXX           LXXXXXXX",
"X  L               O  E C CXXXXX  XXXXX                          XXXXXXX           XXXX                               XXXX             XXXX             LXXXXXXX",
"X  L               XXXXXXXXXXXXX  XXXX                           XXXXXXXXX       XXX                                     XXXXXXXXXXXXXXXX               LXXXXXXX",
"X  L      X        XXXXXXXXXXXXX  XX                              XXXXXXXXXXXL  XX                                                                      LXXXXXXX",
"X  L      XP   X   XXXXXXXXXXXXX                                             L                                                                   LXXX   LXXXXXXX",
"X  L     XXX   X   XXXXXXXXXX                                                L                                                                   LXXX   LXXXXXXX",
"X  L          XXX  XXXX                                                      L                                 XX                                LXXX   LXXXXXXX",
"X  L               XX                                                        L                     XXX  X  XX                 E                  LXXX    XXXXXXX",
"X  L                                                         LXX  XXXX       L     XXXXXXXXXXXXXX                         O       O         XX  XXXXX    XXXXXXX",
"X  L                                                         L    XXXXXXX    L XXXXXXXXXXXXXXXXXX                      XX  XXXXXXX      XX  XX  XXXXX    XXXXXXX",
"X  L                       XXXXX O       E       E     E     L  O XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX  XX  XXXXXXX  XX  XX  XX  XXXXX    XXXXXXX",
"X  L                    XXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTXXTTXXTTXXXXXXXTTXXTTXXTTXXTTXXXXXTTTTXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTXXTTXXTTXXXXXXXTTXXTTXXTTXXTTXXXXXTTTTXXXXXXX"],
