"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXXXXXXXXX",
"X                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXX",
"X                                        XXXXXXXXXXXXX     XXXXXXXXXXXX                   XXXXXXXXX        XXXXXXXXXXX                                 XX",
"X                                        XXXXXXXXXXX             XXXX                                                                                   X",
"X     LXXX      XX                       XXXXXXXXX                                                                                     C  C             X",
"X     L     XX                           XXXXXXXXX  C                         OO      C  E        C   O    E      C    E    C  O       XX XX  XXX       X",
"XC    L                          XXXXXXXXXXXXXXXXX                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXL  X",
"XXXX  L              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXX                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
"X     L                    XXXXXXXXXXXXXXXXXXXXXXX                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
"X     L                         XXXXXXXXXXXXXXXXX            XXX  XX       XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
"X       XXO E  O                        XXXXXXXXX                     XX   XXXXXXXXXXXXXXXX          XXXXXXXX            XXXXXXXXXXXX                L  X",
"X          XXXX                             XXXXX                              XXXXXXXXXXX            XXXXX                  XXXXXXXX                L  X",
"X                XXX  XXL                    XXXX                                XXXXXXXXX            XXXXX                     XXXXX                L  X",
"X                       L            C C C    XXX                                XXXXXXXXX      P     XXXX                       XXXX               XXX X",
"X   LXXXX               L        XX  XXXXX    XXX                                XXXXXXXX              XX                          XX            XX     X",
"X   L     XXXX              XXX                XX                                 XXXXXXX      XXX     XX                                    XX         X",
"X   L           XX XX  XX                      X                                  XXXXXXX              X                               LXXXX            X",
"X   L                                                 C  C                        XXXXXXX                                              LXXXX            X",
"X   L                                                                             XXXXXX                                               LXXXX            X",
"X   L                                                XXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXX                O     E     C   E     E    O   LXXXXTTTTTTTTTTTTX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTX",
