"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX               XXXXXXXXXXXXXXX  O                    O     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O                    O       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O      E     E       O        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXX     LXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXX  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX         P     XXXXXXXXXXXO     L                    OXX       XXXXX       XXXXXXXXXXXXXXXX",
"XXXXXXXXX      XXXXXXXXXXXXXXXXXXXOO     L                    OXXX        XX          XXXXXXXXXXXXXX",
"XXXO        C         O XXXXXXXXXXOO     L     M              OXXXX       XX            XXXXXXXXXXXX",
"XXXO                  O XXXXXXXXX OO     L                    OXXXX                      XXXXXXXXXXX",
"XX O M                O XXXXXXXXX        XXX  XXXXXXL           XXXX                     XXXXXXXXXXX",
"XX O                  OXXXXXXXXX                    L           XXXXX                     XXXXXXXXXX",
"XXXXXXXXX   C  XXXXXXXXXXXXXXXXX                    L           XXXXX                      XXXXXXXXX",
"XX O                  OXXXXXXXX                     L     D     XXXXXX                           XXX",
"XX O                  O XXXXXX                      L    XXX    XXXXXX                            XX",
"XX O                M O XXXXX                       L           XXXXXX                             X",
"XXXO        C         O XXXX                      XXX           XXXXXXX                            X",
"XXXXXXXXX      XXXXXXXXXXXX                 XXXX               XXXXXXXX                   K       XX",
"XXXXXXXXX         O            O LXXXX   X            O    XXXXXXXXXXXXX  XX   XX   X         XXXXXX",
"XXXXXXXX          O            O L       O            O  XXXXXXXXXXXXXXXX             XXXXXXXXXXXXXX",
"XXXXXXXX          O     E      O L       O     E      O XXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX",
