level_map = [["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXX           XXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                              XXXXXXXXXXXXXXXXX                XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXX                                  XXXXXXXXXXXX                     XX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXX                                    XXXXXXXXXX                        X",
"XXXX     XXXXXXXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXXX                  XXXXXXXXX                   O            O      XXXXXXX                          X",
"XXX         XXXXXXXXXX                       XXXXXXXXXXXX                                                 O            O      XXXXXX                           X",
"XXX                                                                                                   C   O      E  E  O      XXXX                             X",
"XXX                                                                                            LXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX                              X",
"XXX                                                                                            L         XXXXXXXXXXXXXXXXX    XX                               X",
"XXX                                                                                            L                 XXXXXXXXX    X                          K     X",
"XX                                                                                             L                              X                                X",
"XX                                                                                             L                                                   LXXXXXXXXXXXX",
"XX                                                                                             L               O        O                          LXXXXXXXXXXXX",
"XX                                                                                 C           L               O        O                          LXXXXXXXXXXXX",
"XX                                                                                             L               O     E  O                          LXXXXXXXXXXXX",
"X                               P            C     O               O  C          XXXX  X  XXXXXXXX   XX   XXX   XXXXXXXX   XXXXXX                  LXXXXXXXXXXXX",
"X                                                  O               O      X  XX           XXXXXXXX              XXXXXXXX   XXXXXX   O             OLXXXXXXXXXXXX",
"X                         XXXXXXXXXXXXX   XXXXXXX  O    E          O XXX                  XXXXXXXX              XXXXXXXX   XXXXXX   O             OLXXXXXXXXXXXX",
"X                         XXXXXXXXXXXXX   XXXXXXX   XXXXXXXXXXXXXXX                       XXXXXXXX              XXXXXXXX   XXXXXX   O     E       OLXXXXXXXXXXXX",
"XTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXTTTXXXXXXXTTTXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXTTTTTTTTTTTTTTXXXXXXXXTTTXXXXXXTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXTTTXXXXXXXTTTXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXTTTTTTTTTTTTTTXXXXXXXXTTTXXXXXXTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                                                                                XXXXXXXXXXXXXXXXXX         XXXXX",
"X                      O            O                                                              XXXXXXXXXXXXX             XXXX",
"X             O        O    E       O       P                                                        XXXXXXXX                 XXX",
"X             O  E     OXXXXXXXXXXXX                                                                  XXXXXX                  XXX",
"X              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXL  XXXXXXXXXXXX   XXXXX                    XXXXXX                   XX",
"X       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       L     XXXXXXXX            XXXXXL           XXXXX                    XX",
"X    C    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             L      XXXXXX                  L           XXXXX               K   XXX",
"X             XXXXXXXXXXXXXXXXXXXXXXXXX                    L       XXXX                   L           XXXXX                  XXXX",
"X                   XXXXXXXXXXXXXXXX                       L       XXXX                   L          XXXXXX           LXXXXXXXXXX",
"X                         XXXXXXXX                         L       XXXX                   L          XXXXXX           L     XXXXX",
"X                           XXXXX                          L        XXX                   L          XXXXXX           L    XXXXXX",
"X    C                       XXXX     O     O   C          L        XXX                   L          XXXXXX           L   XXXXXXX",
"X                             XX      O C  EO XXXXX        L        XXXX                  L         XXXXXXX           L XXXXXXXXX",
"X                              X      LXXXXX               L        XXXX   C      C       L         XXXXXXX      LXXXXXXXXXXXXXXX",
"X                                     L                    L         XXXX                 L        XXXXXXX       L     XXXXXXXXXX",
"X                                     L O       O          L         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          L      XXXXXXXXX",
"X                                     L O   E   O          L           XXXXXXXXXXXXXXXXXXXX                      L       XXXXXXXX",
"X     C                       LXXXX  XXXXXXXXXXX           L                                             O       L   O   XXXXXXXX",
"X          O              O   LXXXX  XXXXXXXXXXX      XXXXXXXXXX   O                         O           O     E L   O  XXXXXXXXX",
"X          O     E   E    O   LXXXXTTXXXXXXXXXXXTTTTTTXXXXXXXXXX   O    E     C       E C  E O  XXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
    ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXXXXXXXXX",
    "X                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXX",
    "X                                        XXXXXXXXXXXXX     XXXXXXXXXXXX                   XXXXXXXXX        XXXXXXXXXXX                                 XX",
    "X                                        XXXXXXXXXXX             XXXX                                                                                   X",
    "X     LXXX      XX                  K    XXXXXXXXX                            OO                      O                        O       C  C             X",
    "X     L     XX                           XXXXXXXXX  C                         OO      C  E        C   O    E      C    E    C  O       XX XX  XXX       X",
    "XC    L                          XXXXXXXXXXXXXXXXX                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXL  X",
    "XXXX  L              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXX                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X     L                    XXXXXXXXXXXXXXXXXXXXXXX                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X     L   O    O                XXXXXXXXXXXXXXXXX            XXX  XX       XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X       XXO E  O                        XXXXXXXXX                     XX   XXXXXXXXXXXXXXXX          XXXXXXXX            XXXXXXXXXXXX                L  X",
    "X          XXXX                             XXXXX                              XXXXXXXXXXX            XXXXX                  XXXXXXXX                L  X",
    "X                XXX  XXL                    XXXX                                XXXXXXXXX            XXXXX                     XXXXX                L  X",
    "X                       L            C C C    XXX                                XXXXXXXXX      P     XXXX                       XXXX               XXX X",
    "X   LXXXX               L        XX  XXXXX    XXX                                XXXXXXXX              XX                          XX            XX     X",
    "X   L     XXXX              XXX                XX                                 XXXXXXX      XXX     XX                                    XX         X",
    "X   L           XX XX  XX                      X                                  XXXXXXX              X                               LXXXX            X",
    "X   L                                                 C  C                        XXXXXXX                                              LXXXX            X",
    "X   L                                                                             XXXXXX  D             O           M              O   LXXXX            X",
    "X   L                                                XXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXX  R             O     E     C   E     E    O   LXXXXTTTTTTTTTTTTX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX               XXXXXXXXXXXXXXX  O                    O     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O                    O       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O      E     E       O        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXX     LXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXX  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX          P    XXXXXXXXXXXO     L                    OXX       XXXXX       XXXXXXXXXXXXXXXX",
"XXXXXXXXX      XXXXXXXXXXXXXXXXXXXOO     L                    OXXX        XX          XXXXXXXXXXXXXX",
"XXXO        C         O XXXXXXXXXXOO     L                    OXXXX       XX            XXXXXXXXXXXX",
"XXXO                  O XXXXXXXXX OO     L     M              OXXXX                      XXXXXXXXXXX",
"XX O M                O XXXXXXXXX        XXX  XXXXXXL           XXXX                     XXXXXXXXXXX",
"XX O                  OXXXXXXXXX                    L           XXXXX                     XXXXXXXXXX",
"XXXXXXXXX   C  XXXXXXXXXXXXXXXXX                    L           XXXXX                      XXXXXXXXX",
"XX O                  OXXXXXXXX                     L     D     XXXXXX                           XXX",
"XX O                  O XXXXXX                      L    XXX    XXXXXX                            XX",
"XX O                M O XXXXX                       L           XXXXXX                             X",
"XXXO        C         O XXXX                      XXX           XXXXXXX                            X",
"XXXXXXXXX      XXXXXXXXXXXX                 XXXX               XXXXXXXX                   K       XX",
"XXXXXXXXX         O            O LXXXX   X            O    XXXXXXXXXXXXX  XX   XX   X         XXXXXX",
"XXXXXXXX          O            O L       O            O  XXXXXXXXXXXXXXXX             XXXXXXXXXXXXXX",
"XXXXXXXX          O     E      O L       O     E      O XXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX"]]



# во сколько раз увеличивать все спрайты
scaling = 2
tile_size = 16 * scaling
screen_width = 1280
screen_height = tile_size * 22

