level_map = [["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXX                                                            X",
            "XXXXXXXXX          XXXXXXXXXXXXX          XXXXXX                                                              X",
            "XXXXXXX             XXXXXXXXXXXX          XXXX                                C                               X",
            "XXXXX                      XXXXXXCE                                           XXL                             X",
            "XXX                           XXXXXXXXXXL                                                                     X",
            "XXX                                     L                   C                                                 X",
            "XX                                      L               LXXXXXXXXXX  XX  XX      XX                           X",
            "XX                                      L               LXXXXXXXXX           XX                               X",
            "X                               C  C  C L               L                                                     X",
            "X                XX          XXXXXXXXXXXXXXX            L                                                     X",
            "X       XX  XXX         XXX    XXXXXXXXXXX              L                                                     X",
            "XXXXXXL             XX                         XXX  LXXXX                           LXXXX             XXXXXXXXX",
            "XXXXX L                                             LXXXX                           LXXXX          XXXXXXXXXXXX",
            "XX    L                                             L                               LXXXX       XXXXXXXXXXXXXXX",
            "XX    L                                             L                               LXXXX    XXXXXXXXXXXXXXXXXX",
            "X     L                    XX O     E     O         L                               LXXXX  XXXXXXXXXXXXXXXXXXXX",
            "X     L            XX  XX  XX  XXXXXXXXXXX  XXXXXXXXX                               LXXXX  XXXXXXXXXXXXXXXXXXXX",
            "X     L      P     XX  XX  XX  XXXXXXXXXXX  XXXXXXXXX                               LXXXX  XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXX  XX  XX  XX  XXXXXXXXXXX  XXXXXXXXX    O  C EC  C E  OOE OO E O   LXXXX  XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXTTXXXXXTTXXTTXXTTXXTTXXXXXXXXXXX  XXXXXXXXXTTTTTXXXXXXXXXXXXXTTXXTTXXXTTXXXXXXXTTXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXTTXXXXXTTXXTTXXTTXXTTXXXXXXXXXXX  XXXXXXXXXTTTTTXXXXXXXXXXXXXTTXXTTXXXTTXXXXXXXTTXXXXXXXXXXXXXXXXXXXX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                  XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
"X                  XXXXXXXXXXXX XXXXXXXXXXXXX         XXXXXXXXXXXXXXXXX                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X",
"X                  XXXXXXXXXXX   XXXXXXXXXX              XXXXXXXXXXXXX                                                                 XXXXXXXXXXX             X",
"X                  XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXX                                                                   XXXXXXXX               X",
"X                  XXXXXXXXXXXXXXXXXXXXXXXO E                XXXXXXXX                                                        X   X  X X  XXXXXXX               X",
"X             XXX  XXXXXXXXXXXXXXXXXXXXXXX XXXX               XXXXXXX                                                       X X X X  X   XXXXXX                X",
"X        XXX               XXXXXXXXXXXXXX                      XXXXXX                              O  E         O           X X  X  X X  XXXXX          LXXXXXXX",
"X  LXXX                    XXXXXXXXXXXXXX            E  E O     XXXXX                O      E       XXXXXXXXXXXX   E  O                  XXXXX          LXXXXXXX",
"X  L                       XXXXX  XXXXXX            XXXXXX      XXXXXX                XXXXXXXXXXXXXX            XXXXXX                  XXXXX           LXXXXXXX",
"X  L               O  E C CXXXXX  XXXXX                          XXXXXXX           XXXX                               XXXX             XXXX             LXXXXXXX",
"X  L               XXXXXXXXXXXXX  XXXX                           XXXXXXXXX       XXX                                     XXXXXXXXXXXXXXXX               LXXXXXXX",
"X  L      X        XXXXXXXXXXXXX  XX                              XXXXXXXXXXXL  XX                                                                      LXXXXXXX",
"X  L      XP   X   XXXXXXXXXXXXX                                             L                                                                   LXXX   LXXXXXXX",
"X  L     XXX   X   XXXXXXXXXX                                                L                                                                   LXXX   LXXXXXXX",
"X  L          XXX  XXXX                                                      L                                 XX                                LXXX   LXXXXXXX",
"X  L               XX                                                        L                     XXX  X  XX                 E                  LXXX    XXXXXXX",
"X  L                                                         LXX  XXXX       L     XXXXXXXXXXXXXX                         O       O         XX  XXXXX    XXXXXXX",
"X  L                                                         L    XXXXXXX    L XXXXXXXXXXXXXXXXXX                      XX  XXXXXXX      XX  XX  XXXXX    XXXXXXX",
"X  L                       XXXXX O       E       E     E     L  O XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX  XX  XXXXXXX  XX  XX  XX  XXXXX    XXXXXXX",
"X  L                    XXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTXXTTXXTTXXXXXXXTTXXTTXXTTXXTTXXXXXTTTTXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTXXTTXXTTXXXXXXXTTXXTTXXTTXXTTXXXXXTTTTXXXXXXX"],
    ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXXXXXXXXX",
    "X                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXX",
    "X                                        XXXXXXXXXXXXX     XXXXXXXXXXXX                   XXXXXXXXX        XXXXXXXXXXX                                 XX",
    "X                                        XXXXXXXXXXX             XXXX                                                                                   X",
    "X     LXXX      XX                       XXXXXXXXX                            OO                      O                        O       C  C             X",
    "X     L     XX                           XXXXXXXXX  C                         OO      C  E        C   O    E      C    E    C  O       XX XX  XXX       X",
    "XC    L                          XXXXXXXXXXXXXXXXX                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX              XXL  X",
    "XXXX  L              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXX                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X     L                    XXXXXXXXXXXXXXXXXXXXXXX                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X     L   O    O                XXXXXXXXXXXXXXXXX            XXX  XX       XXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                L  X",
    "X       XXO E  O                        XXXXXXXXX                     XX   XXXXXXXXXXXXXXXX          XXXXXXXX            XXXXXXXXXXXX                L  X",
    "X          XXXX                             XXXXX                              XXXXXXXXXXX            XXXXX                  XXXXXXXX                L  X",
    "X                XXX  XXL                    XXXX                                XXXXXXXXX            XXXXX                     XXXXX                L  X",
    "X                       L            C C C    XXX                                XXXXXXXXX      P     XXXX                       XXXX               XXX X",
    "X   LXXXX               L        XX  XXXXX    XXX                                XXXXXXXX              XX                          XX            XX     X",
    "X   L     XXXX              XXX                XX                                 XXXXXXX      XXX     XX                                    XX         X",
    "X   L           XX XX  XX                      X                                  XXXXXXX              X                               LXXXX            X",
    "X   L                                                 C  C                        XXXXXXX                                              LXXXX            X",
    "X   L                                                                             XXXXXX                O                          O   LXXXX            X",
    "X   L                                                XXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXX                O     E     C   E     E    O   LXXXXTTTTTTTTTTTTX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTX",]]



# во сколько раз увеличивать все спрайты
scaling = 2
tile_size = 16 * scaling
screen_width = 1280
screen_height = tile_size * 22

