level_map = [["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXX           XXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                              XXXXXXXXXXXXXXXXX                XXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXX                                  XXXXXXXXXXXX                     XX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXX                                    XXXXXXXXXX                        X",
"XXXX     XXXXXXXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXXX                  XXXXXXXXX                   O            O      XXXXXXX                          X",
"XXX         XXXXXXXXXX                       XXXXXXXXXXXX                                                 O            O      XXXXXX                           X",
"XXX                                                                                                   C   O      E  E  O      XXXX                             X",
"XXX                                                                                            LXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX                              X",
"XXX                                                                                            L         XXXXXXXXXXXXXXXXX    XX                               X",
"XXX                                                                                            L                 XXXXXXXXX    X                          K     X",
"XX                                                                                             L                              X                                X",
"XX                                                                                             L                                                   LXXXXXXXXXXXX",
"XX                                                                                             L               O        O                          LXXXXXXXXXXXX",
"XX                                                                                C            L               O        O                          LXXXXXXXXXXXX",
"XX                                                                                             L               O     E  O                          LXXXXXXXXXXXX",
"X                               P            C     O               O  C          XX   X   XXXXXXXX   XX   XXX   XXXXXXXX   XXXXXX                  LXXXXXXXXXXXX",
"X                                                  O               O      X  XX           XXXXXXXX              XXXXXXXX   XXXXXX   O             OLXXXXXXXXXXXX",
"X                         XXXXXXXXXXXXX   XXXXXXX  O    E          O XXX                  XXXXXXXX              XXXXXXXX   XXXXXX   O             OLXXXXXXXXXXXX",
"X                         XXXXXXXXXXXXX   XXXXXXX   XXXXXXXXXXXXXXX                       XXXXXXXX              XXXXXXXX   XXXXXX   O     E       OLXXXXXXXXXXXX",
"XTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXTTTXXXXXXXTTTXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXTTTTTTTTTTTTTTXXXXXXXXTTTXXXXXXTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXTTTXXXXXXXTTTXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXTTTTTTTTTTTTTTXXXXXXXXTTTXXXXXXTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                                                                                XXXXXXXXXXXXXXXXXX         XXXXX",
"X                      O            O                                                              XXXXXXXXXXXXX             XXXX",
"X             O        O    E       O       P                                                        XXXXXXXX                 XXX",
"X             O  E     OXXXXXXXXXXXX                                                                  XXXXXX                  XXX",
"X              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXL  XXXXXXXXXXXX   XXXXX                    XXXXXX                   XX",
"X       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       L     XXXXXXXX            XXXXXL           XXXXX                    XX",
"X    C    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             L      XXXXXX                  L           XXXXX               K   XXX",
"X             XXXXXXXXXXXXXXXXXXXXXXXXX                    L       XXXX                   L           XXXXX                  XXXX",
"X                   XXXXXXXXXXXXXXXX                       L       XXXX                   L          XXXXXX           LXXXXXXXXXX",
"X                         XXXXXXXX                         L       XXXX                   L          XXXXXX           L     XXXXX",
"X                           XXXXX                          L        XXX                   L          XXXXXX           L    XXXXXX",
"X    C                       XXXX     O     O   C          L        XXX                   L          XXXXXX           L   XXXXXXX",
"X                             XX      O C  EO XXXXX        L        XXXX                  L         XXXXXXX           L XXXXXXXXX",
"X                              X      LXXXXX               L        XXXX   C      C       L         XXXXXXX      LXXXXXXXXXXXXXXX",
"X                                     L                    L         XXXX                 L        XXXXXXX       L     XXXXXXXXXX",
"X                                     L O       O          L         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          L      XXXXXXXXX",
"X                                     L O   E   O          L           XXXXXXXXXXXXXXXXXXXX                      L       XXXXXXXX",
"X     C                       LXXXX  XXXXXXXXXXX           L                                             O       L   O   XXXXXXXX",
"X          O              O   LXXXX  XXXXXXXXXXX      XXXXXXXXXX   O                         O           O     E L   O  XXXXXXXXX",
"X          O     E   E    O   LXXXXTTXXXXXXXXXXXTTTTTTXXXXXXXXXX   O    E     C       E C  E O  XXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
    ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXX                                      XXXXX                O         O      XXXXXXXXXXXXX",
"XXX O                                   O  XXX                 O         O               XXXX",
"XX  O                                   O   XX     C    C      O     C   O                XXX",
"XX  O                        M          O   XX                 O  E    XXXXX              XXX",
"X                                            X  LXXXXXXXXXXXX   XXXXXXXXXXXXO        O    XXX",
"X                                            X  L                         XXO        O     XX",
"X                                            X  L                         XXO  E     O     XX",
"X                                            X  L O         O             XXXXXXXXXXXX     XX",
"XX                                           X  L O         O             XX              XXX",
"XX                                           X    O E   E   O           XXXX              XXX",
"XXX                                               XXXXXXXXXX              XX              XXX",
"XXXXXX    P                                                    XXXXXXL    XX              XXX",
"XXXXXXXXXXXXXXXXXXX                                                  L   OXX    K         XXX",
"XXXXXXXXXXXXXXXXXXX             C   C   C        O                   L   OXXX             XXX",
"XXXXXXXXXXXXXXXXXXX                              O                   L   OXXX  XXXX   XX  XXX",
"XXXXXXXXXXXXXXXXXXX    XXXXXX   X   X   X   XXX  O                   L   OXXXX            XXX",
"XXXXXXXXXXXXXXXXXXX    XXXXXX               XXX  O           M       L    XXXX           XXXX",
"XXXXXXXXXXXXXXXXXXX    XXXXXX               XXX  XXX   XXX   XXX   XXX  XXXXXX           XXXX",
"XXXXXXXXXXXXXXXXXXX    XXXXXX               XXX                        XXXXXXXX          XXXX",
"XXXXXXXXXXXXXXXXXXXTTTTXXXXXXTTTTTTTTTTTTTTTXXXTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXTTTTTTTTTXXXX",
"XXXXXXXXXXXXXXXXXXXTTTTXXXXXXTTTTTTTTTTTTTTTXXXTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXTTTTTTTTTXXXX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX               XXXXXXXXXXXXXXX  O                    O     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O                    O       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXXXX   O      E     E       O        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX                 XXXXXXXXXXX     LXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXX  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXX         P     XXXXXXXXXXXO     L                    OXX       XXXXX       XXXXXXXXXXXXXXXX",
"XXXXXXXXX      XXXXXXXXXXXXXXXXXXXOO     L                    OXXX        XX          XXXXXXXXXXXXXX",
"XXXO        C         O XXXXXXXXXXOO     L                    OXXXX       XX            XXXXXXXXXXXX",
"XXXO                  O XXXXXXXXX OO     L     M              OXXXX                      XXXXXXXXXXX",
"XX O M                O XXXXXXXXX        XXX  XXXXXXL           XXXX                     XXXXXXXXXXX",
"XX O                  OXXXXXXXXX                    L           XXXXX                     XXXXXXXXXX",
"XXXXXXXXX   C  XXXXXXXXXXXXXXXXX                    L           XXXXX                      XXXXXXXXX",
"XX O                  OXXXXXXXX                     L     D     XXXXXX                           XXX",
"XX O                  O XXXXXX                      L    XXX    XXXXXX                            XX",
"XX O                M O XXXXX                       L           XXXXXX                             X",
"XXXO        C         O XXXX        C             XXX           XXXXXXX                            X",
"XXXXXXXXX      XXXXXXXXXXXX                 XXXX               XXXXXXXX                   K       XX",
"XXXXXXXXX         O            O LXXXX   X            O    XXXXXXXXXXXXX  XX   XX   X         XXXXXX",
"XXXXXXXX          O            O L       O            O  XXXXXXXXXXXXXXXX             XXXXXXXXXXXXXX",
"XXXXXXXX          O     E      O L       O     E      O XXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTXXXXXXXXXXXXXX"],
["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                                        XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXX     XXXXXXXX                                                                                                                                                                XXXXXXXX     XXXXXXX",
"XXXXX                                         O                                                                                                          O                                         XXXXX",
"XXXX           OO        O                    O                           O                                                  O                           O                    O        OO           XXXX",
"XXX            OO        O                    O                        C  O                                                  O  C                        O                    O        OO            XXX",
"XXX            OO E   E  O                   OO    E       M      E       O                                                  O       E      M       E    OO                   O  E   E OO            XXX",
"XX               XXXXXXXX   X   X   XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXL                                                  LXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX   X   X   XXXXXXXX               XX",
"X                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    L                                                  L    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                        X",
"X                                          XXXXXXXXXXXXXXXXXXXXXXXX       L                                                  L       XXXXXXXXXXXXXXXXXXXXXXXX                                          X",
"X                                           XXXXXXXXXXXXXXXXXXXXXX        L    O       O                        O       O    L        XXXXXXXXXXXXXXXXXXXXXX                                           X",
"X    K                                      XXXXXXXXXXXXXX  XXXXX         L    O C   C O  C       P          C  O C   C O    L         XXXXX  XXXXXXXXXXXXXX                                      K    X",
"X                                           XXXXX   XXXXX     XX          L    O  E    O                        O    E  O    L          XX     XXXXX   XXXXX                                           X",
"X                                            XXXX              X          XXX  OXXXXXXXO  X   XXXXXXXXXXXX   X  OXXXXXXXO  XXX          X              XXXX                                            X",
"XXXXXXXXXXXX                                  XX                          XXX                 XX        XX                 XXX                          XX                                  XXXXXXXXXXXX",
"XXXXXXXXXXXXXX                                                            XXX                 X          X                 XXX                                                            XXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX   X   XX   X   XXX XXL                                    XXX                 X          X                 XXX                                    LXX XXX   X   XX   X   XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX                    XXL O                       O          XXX                 X          X                 XXX          O                       O LXX                    XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX                    XXL O                       O          XXX                 X          X                 XXX          O                       O LXX                    XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX                    XXL O                       O          XXX                 X          X                 XXX          O                       O LXX                    XXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTXXL O  E                 E  O        D XXXTTTTTTTTTTTTTTTTTXTTTTTTTTTTXTTTTTTTTTTTTTTTTTXXX R        O  E                 E  O LXXTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTXTTTTTTTTTTXTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXXXXX"]]



# во сколько раз увеличивать все спрайты
scaling = 2
tile_size = 16 * scaling
screen_width = 1280
screen_height = tile_size * 22

